### ISSUE TITLE
How does the send_message work

### ISSUE THREAD

**Issue by Jantje2000** [ssjoholm/rfxcmd_gc#2]
Hi,

Momentally I'm trying to use the send_message function. But now the problem is: This program will say every time that the raw data is missing. Which data have I to send?

**Comment by k-mooijman** [comment]
This worked for me .

i got from the command `python rfxcmd.py -l -v -d /dev/ttyUSB0`

```
Received                = 0B 11 00 00 00 A6 C7 0A 01 00 00 70
Date/Time               = 2017-02-04 11:26:00
Packet Length           = 0B
Packettype              = Lighting2
Subtype                 = AC
Seqnbr                  = 00
Id                      = 00A6C70A
Unitcode                = 1
Command                 = Off
Dim level               = 0%
Signal level            = 7

```

using the Received data without the spaces made : 

`python rfxcmd.py -d /dev/ttyUSB0 -s 0B11000000A6C70A01000070 -v `

**Comment by Jantje2000** [comment]
Thanks
